#!/bin/bash

if [[ -v TGIT_LOG ]]; then
    echo "$@" >> /tmp/tgit-command.log
fi

export WINEPREFIX=~/.wine-tortoise
wine "C:\Program Files\TortoiseGit\bin\TortoiseGitProc.exe" /command:$1 /path:`winepath -w "$2"` "${@:3}" &